services:
  # database
  db:
    image: postgres:13 
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s 
      timeout: 5s 
      retries: 5

  # flask backend 
  backend: 
    build: ./backend 
    ports: 
      - "5001:5000" 
    volumes: 
      - ./backend:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development 
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
    depends_on: 
      - db 

  # react/vite frontend 
  frontend: 
    build: ./frontend 
    ports: 
      - "5173:5173" 
    volumes: 
      - ./frontend:/app 
      - /app/node_modules 
    depends_on:
      - backend 
    network_mode: "host"
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5000 

volumes:
  postgres_data:

