"""Add Stock and Trade tables

Revision ID: 3598ba5cb36a
Revises: 
Create Date: 2025-05-01 03:36:34.017164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3598ba5cb36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_name', sa.String(length=128), nullable=False),
    sa.Column('politician_family', sa.String(length=128), nullable=True),
    sa.Column('politician_link', sa.String(length=256), nullable=True),
    sa.Column('traded_issuer_name', sa.String(length=256), nullable=False),
    sa.Column('traded_issuer_ticker', sa.String(length=32), nullable=True),
    sa.Column('traded_issuer_link', sa.String(length=256), nullable=True),
    sa.Column('published', sa.String(length=64), nullable=True),
    sa.Column('traded', sa.Date(), nullable=True),
    sa.Column('filed_after', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('stock')
    # ### end Alembic commands ###
