"""add stock profile fields

Revision ID: 55100f66c082
Revises: 9d6d54ee671a
Create Date: 2025-05-04 06:11:35.537172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55100f66c082'
down_revision = '9d6d54ee671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('estimate_currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('ipo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('market_capitalization', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('shares_outstanding', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weburl', sa.String(length=256), nullable=True))
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('weburl')
        batch_op.drop_column('shares_outstanding')
        batch_op.drop_column('phone')
        batch_op.drop_column('market_capitalization')
        batch_op.drop_column('logo')
        batch_op.drop_column('ipo')
        batch_op.drop_column('estimate_currency')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
