"""Database

Revision ID: e1a2fbe0e69f
Revises: 
Create Date: 2025-05-26 18:01:54.639451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a2fbe0e69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politician_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_name', sa.String(length=128), nullable=False),
    sa.Column('politician_family', sa.String(length=128), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('estimate_currency', sa.String(length=8), nullable=True),
    sa.Column('ipo', sa.Date(), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('weburl', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_name', sa.String(length=128), nullable=False),
    sa.Column('politician_family', sa.String(length=128), nullable=True),
    sa.Column('politician_link', sa.String(length=256), nullable=True),
    sa.Column('traded_issuer_name', sa.String(length=256), nullable=False),
    sa.Column('traded_issuer_ticker', sa.String(length=32), nullable=True),
    sa.Column('traded_issuer_link', sa.String(length=256), nullable=True),
    sa.Column('published', sa.String(length=64), nullable=True),
    sa.Column('traded', sa.Date(), nullable=True),
    sa.Column('filed_after', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('10d_avg_vol', sa.Float(), nullable=True),
    sa.Column('13w_ret', sa.Float(), nullable=True),
    sa.Column('52w_high', sa.Float(), nullable=True),
    sa.Column('52w_high_dt', sa.Date(), nullable=True),
    sa.Column('52w_low', sa.Float(), nullable=True),
    sa.Column('52w_low_dt', sa.Date(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ps_ttm', sa.Float(), nullable=True),
    sa.Column('dividend_yield_ttm', sa.Float(), nullable=True),
    sa.Column('current_ratio_quarterly', sa.Float(), nullable=True),
    sa.Column('quick_ratio_quarterly', sa.Float(), nullable=True),
    sa.Column('roe_ttm', sa.Float(), nullable=True),
    sa.Column('roa_ttm', sa.Float(), nullable=True),
    sa.Column('eps_ttm', sa.Float(), nullable=True),
    sa.Column('rev_per_share_ttm', sa.Float(), nullable=True),
    sa.Column('rev_growth_ttm_yoy', sa.Float(), nullable=True),
    sa.Column('eps_growth_ttm_yoy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('adj_high', sa.Float(), nullable=True),
    sa.Column('adj_low', sa.Float(), nullable=True),
    sa.Column('adj_open', sa.Float(), nullable=True),
    sa.Column('adj_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_price')
    op.drop_table('stock_metric')
    op.drop_table('trade')
    op.drop_table('stock')
    op.drop_table('politician_img')
    # ### end Alembic commands ###
