"""testing

Revision ID: f25c02e3ff13
Revises: 42ad50352366
Create Date: 2025-05-20 20:13:55.855423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25c02e3ff13'
down_revision = '42ad50352366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politician_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_name', sa.String(length=128), nullable=False),
    sa.Column('politician_family', sa.String(length=128), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politician_img')
    # ### end Alembic commands ###
