"""Add trade table

Revision ID: f66f1bc2c313
Revises: f8dc87c9f784
Create Date: 2025-04-30 06:05:57.310602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66f1bc2c313'
down_revision = 'f8dc87c9f784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_name', sa.String(length=255), nullable=True),
    sa.Column('politician_family', sa.String(length=255), nullable=True),
    sa.Column('politician_link', sa.String(length=255), nullable=True),
    sa.Column('traded_issuer_name', sa.String(length=255), nullable=True),
    sa.Column('traded_issuer_ticker', sa.String(length=20), nullable=True),
    sa.Column('traded_issuer_link', sa.String(length=255), nullable=True),
    sa.Column('published', sa.String(length=50), nullable=True),
    sa.Column('traded', sa.String(length=50), nullable=True),
    sa.Column('filed_after', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    # ### end Alembic commands ###
